# Sesión 15 · Matrices y álgebra lineal aplicada

Badge 5 · Procesamiento de datos en Python

Domina dimensiones, productos matriciales y sistemas lineales con arreglos de NumPy.

150 minutos de clase; tarea de 45–60 minutos. Ejecuta en orden.

## Forma, transposición y producto

Usa ndarray bidimensional para matrices. * multiplica elemento por elemento; @ realiza producto matricial. Para A de forma (m,n) y B de forma (n,p), A @ B tiene forma (m,p).

reshape reorganiza una cantidad compatible de elementos; .T transpone ejes en una matriz. Una transposición puede ser una vista de los mismos datos: usa copy si necesitas independencia.

In [1]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[2,0],[0,2]])
print(A*B)
print(A@B)
print(A.T)

[[2 0]
 [0 8]]
[[2 4]
 [6 8]]
[[1 3]
 [2 4]]


**Qué observar:** Elemento a elemento: [[2,0],[0,8]]. Matricial: [[2,4],[6,8]].

**Recuerda:** Comprueba shapes antes de operar. No necesitas np.matrix.

## Broadcasting: compatibilidad, no magia

NumPy compara dimensiones desde la derecha: deben coincidir o una debe ser 1. Una media por columna con keepdims=True tiene forma (1,n) y puede restarse de una matriz (m,n).

Para estandarizar, resta media y divide por desviación. Una columna constante tiene desviación cero: define una política antes de dividir. En modelado, ajusta estas estadísticas solo con entrenamiento.

In [2]:
import numpy as np
X=np.array([[1.,10.],[3.,20.],[5.,30.]])
media=X.mean(axis=0,keepdims=True)
escala=X.std(axis=0,keepdims=True)
Z=(X-media)/np.where(escala==0,1,escala)
print(media.shape)
print(np.round(Z.mean(axis=0),6))

(1, 2)
[0. 0.]


**Qué observar:** La media tiene forma (1,2); las medias estandarizadas son [0,0].

**Recuerda:** Broadcasting no implica que las dimensiones tengan significado compatible: verifica unidades y ejes.

## Resolver y verificar

np.linalg.solve encuentra x para A @ x = b si A es cuadrada y de rango completo. Evita calcular la inversa explícitamente solo para resolver el sistema.

Un residuo pequeño confirma que la solución satisface aproximadamente la ecuación. Un sistema mal condicionado puede amplificar errores; revisa cond y considera el contexto. Para un sistema rectangular se estudia lstsq como extensión.

In [3]:
import numpy as np
A=np.array([[2.,1.],[1.,3.]])
b=np.array([5.,10.])
x=np.linalg.solve(A,b)
print(x)
print(np.allclose(A@x,b))
print(np.linalg.norm(A@x-b))

[1. 3.]
True
0.0


**Qué observar:** x=[1,3]; verificación True; residuo cercano a cero.

**Recuerda:** Un residuo pequeño no elimina por sí solo problemas de condicionamiento.

## Reto · Ingresos con una matriz

Filas de cantidades [[2,3],[1,4]] y precios [10,20]. Calcula ingreso por fila.

**Criterio:** [80,90].

In [ ]:
# Tu solución aquí.

## Reto · Centra por columna

Centra [[1,10],[3,20]] restando su media por columna.

**Criterio:** [[-1,-5],[1,5]].

In [ ]:
# Tu solución aquí.

## Tarea · Laboratorio · Matrices y broadcasting

Domina dimensiones, productos matriciales y sistemas lineales con arreglos de NumPy.

1. Crea cantidades de tres sucursales por dos productos y calcula ingreso con @.
2. Estandariza por columna, explicando eje y tratamiento de constantes.
3. Resuelve un sistema 2×2 y mide el residuo.
4. Incluye un ejemplo de formas incompatibles y explica cómo corregir el diseño.

In [ ]:
# Desarrolla tu tarea y explica los resultados.