# Sesión 14 · Calcula con colecciones numéricas

Badge 5 · Procesamiento de datos en Python

Realiza operaciones sobre arreglos y comprende sus dimensiones.

150 minutos de clase; tarea de 45–60 minutos. Ejecuta en orden.

## De una lista a un arreglo

Un arreglo de NumPy organiza valores de un tipo compatible y permite operaciones numéricas sobre todos sus elementos. Multiplicar una lista por dos repite sus elementos; multiplicar un arreglo por dos duplica cada valor.

La vectorización expresa una operación para el conjunto, sin escribir un ciclo explícito. Esto facilita leer la intención del cálculo.

In [1]:
import numpy as np

lista = [2, 4, 6]
arreglo = np.array(lista)
print(lista * 2)
print(arreglo * 2)
print(arreglo.mean())

[2, 4, 6, 2, 4, 6]
[ 4  8 12]
4.0


**Qué observar:** La lista se repite: [2, 4, 6, 2, 4, 6]. El arreglo produce [4, 8, 12]. Su media es 4.0.

**Recuerda:** No asumas que dos objetos responden igual al mismo operador: revisa su tipo.

## Forma, posiciones y ejes

shape indica cuántos elementos hay en cada dimensión. Una matriz de 2 × 3 tiene dos filas y tres columnas. El acceso [fila, columna] usa posiciones desde cero.

En una tabla bidimensional, sum(axis=0) suma a través de las filas y devuelve un total por columna. sum(axis=1) suma las columnas y devuelve un total por fila.

In [2]:
import numpy as np

matriz = np.array([[2, 4, 6], [1, 3, 5]])
print(matriz.shape)
print(matriz[1, 0])
print(matriz.sum(axis=0))
print(matriz.sum(axis=1))

(2, 3)
1
[ 3  7 11]
[12  9]


**Qué observar:** (2, 3); 1; [3, 7, 11]; [12, 9].

**Recuerda:** Describe la salida con palabras antes de elegir el eje: ¿necesitas un resultado por fila o por columna?

## Máscaras y datos de simulación

Una comparación sobre un arreglo produce valores booleanos. Se pueden usar como máscara para conservar elementos que cumplen una condición.

Un generador con semilla permite repetir una simulación en el mismo entorno. No convierte los datos simulados en evidencia del mundo real. El límite superior de integers es exclusivo.

In [3]:
import numpy as np

precios = np.array([500, 1500, 600, 1200])
print(precios[precios > 700])
rng = np.random.default_rng(42)
simulacion = rng.integers(1, 6, size=5)
print(simulacion)
print(np.all((simulacion >= 1) & (simulacion <= 5)))

[1500 1200]
[1 4 4 3 3]
True


**Qué observar:** El filtro devuelve [1500, 1200]. La simulación contiene cinco enteros entre 1 y 5; la comprobación es True.

**Recuerda:** Fija la semilla y registra las versiones si necesitas reproducir una simulación con precisión.

## Reto · Ingresos vectorizados

Crea precios [1500, 500, 600] y cantidades [4, 10, 2] como arreglos. Calcula ingresos y total.

**Criterio:** [6000, 5000, 1200] y total 12200.

In [ ]:
# Tu solución aquí.

## Reto · Filtra temperaturas

De [18, 22, 25, 19, 28], conserva las temperaturas >= 22 y calcula su media.

**Criterio:** [22, 25, 28] y media 25.0.

In [ ]:
# Tu solución aquí.

## Tarea · Semana de temperaturas

Usa [21, 23, 22, 24, 25, 20, 19] como temperaturas diarias en °C.

1. Crea un arreglo y muestra su forma.
2. Calcula mínimo, máximo y media.
3. Selecciona los días con temperatura mayor que 22.
4. Explica por qué filtrar modifica el conjunto sobre el cual se calcula la media.

In [ ]:
# Desarrolla tu tarea y explica los resultados.